### ISSUE TITLE
error using custom scoring file when running pgscatalog/pgsc_calc

### ISSUE THREAD

**Issue by Wenjie-Ma-ScD** [PGScatalog/pygscatalog#34]
Hi,

I encountered an error using my own scoring file when I run pgscatalog/pgsc_calc. Below please find the code and error message. It worked perfectly when I replaced the scorefile with a published pgs_id (PGS001229). Could you help me look into this? Thank you so much!

```
./nextflow run pgscatalog/pgsc_calc -profile singularity \
  -c /n/home15/wma/harvard_dd_pgsc_calc/nextflow.config \
  --input "/n/home15/wma/harvard_dd_pgsc_calc/samplesheet.csv" \
  --scorefile "/n/home15/wma/harvard_dd_pgsc_calc/prscsx_combined-weight-file-forpgsccalc_MVPUKB-EURAFR-Ch38.txt" \
  --target_build GRCh38 \
  --outdir "/n/home15/wma/harvard_dd_pgsc_calc/" \
  --run_ancestry "/n/home15/wma/harvard_dd_pgsc_calc/pgsc_HGDP+1kGP_v1.tar.zst" \
  --min_overlap 0.0 \
  --parallel \
  -resume
```

```
Command error:
  pgscatalog.core.cli.combine_cli: 2024-07-29 15:41:07 DEBUG    Verbose logging enabled
  pgscatalog.core.cli.combine_cli: 2024-07-29 15:41:07 DEBUG    Compressing output with gzip
  Traceback (most recent call last):
    File "/app/pgscatalog.utils/.venv/bin/pgscatalog-combine", line 8, in <module>
      sys.exit(run())
               ^^^^^
    File "/app/pgscatalog.core/src/pgscatalog/core/cli/combine_cli.py", line 39, in run
      scoring_files = sorted([ScoringFile(x) for x in paths], key=lambda x: x.pgs_id)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/app/pgscatalog.core/src/pgscatalog/core/cli/combine_cli.py", line 39, in <listcomp>
      scoring_files = sorted([ScoringFile(x) for x in paths], key=lambda x: x.pgs_id)
                              ^^^^^^^^^^^^^^
    File "/app/pgscatalog.core/src/pgscatalog/core/lib/scorefiles.py", line 238, in __init__
      self._init_from_path(target_build=target_build)
    File "/app/pgscatalog.core/src/pgscatalog/core/lib/scorefiles.py", line 301, in _init_from_path
      raise ScoreFormatError("Missing pgs_id from header")
  pgscatalog.core.lib.pgsexceptions.ScoreFormatError: Missing pgs_id from header
```

**Comment by smlmbrt** [comment]
Looks l

**Comment by smlmbrt** [comment]
Looks like your scoring file is "`Missing pgs_id from header `". You need to add some custom header fields and perhaps column names to the header so that the pipeline can interpret the score correctly (see https://pgsc-calc.readthedocs.io/en/latest/how-to/calculate_custom.html#scorefile-setup).

**Comment by nebfield** [comment]
[See here for a custom scoring file with the correct header format](https://github.com/PGScatalog/pygscatalog/blob/main/pgscatalog.core/tests/data/custom.txt). There's a small mistake in the [docs](https://pgsc-calc.readthedocs.io/en/latest/how-to/calculate_custom.html#scorefile-setup) that will be fixed soon 👀

**Comment by Wenjie-Ma-ScD** [comment]
Thank you! it worked after adding the pgs_id in the header of the score file.
